use NexGenTesting
SELECT LOANACCOUNTNO,DBO.FN_GETLOANPRINCIPLEBALANCE(LOANACCOUNTNO) BAL INTO #TEMP FROM NexGenTesting..LMTLOANISSUE
WHERE TRANSSTATUS='i'

SELECT ACCTNO,LBALPRINC INTO #TEMP1 fROM FinAct..LOAN

SELECT  * into #test fROM #TEMP t JOIN #TEMP1 T1 ON T.LOANACCOUNTNO=T1.ACCTNO
WHERE T.BAL!=T1.LBALPRINC

select * from #test

select * from LmtLoanIssue
where LoanAccountNo in (select LoanAccountNo from #test)

DROP TABLE #TEMP
DROP TABLE #TEMP1
DROP TABLE #test