use nexgencosysdbdev
update MemMemberRegistration
set memberid=replace(memberid,'-02-00000','-02-')
update MemMemberRegistration
set memberid=replace(memberid,'-02-0000','-02-')
update MemMemberRegistration
set memberid=replace(memberid,'-02-000','-02-')
update MemMemberRegistration
set memberid=replace(memberid,'-02-00','-02-')
update MemMemberRegistration
set memberid=replace(memberid,'-02-0','-02-')
update MamAccountOpening
set accountno=replace(AccountNo,'-02-000','-02-')
update MamAccountOpening
set accountno=replace(AccountNo,'-02-00','-02-')
update MamAccountOpening
set accountno=replace(AccountNo,'-02-0','-02-')
update lmtloanissue 
set loanaccountno=replace(loanaccountno,'-02-000','-02-')
update lmtloanissue 
set loanaccountno=replace(loanaccountno,'-02-00','-02-')
update lmtloanissue 
set loanaccountno=replace(loanaccountno,'-02-0','-02-')