USE NEXGENCOSYSDBDEV


		INSERT INTO NexGenCoSysDBDev.dbo.SycRelation SELECT DISTINCT(NRelation),0,GETDATE(),NULL,NULL FROM KAMANA.DBO.Nominee WHERE NRelation IS NOT NULL 	
		AND  NRelation NOT IN (SELECT RELATION FROM SycRelation)



	